import pygame
import time

notes = {
    'r': 'silence.wav',

    'C8': 'do_c8.ogg',

    'C7': 'do_c7.ogg',
    'C#7': 'do_c7_sharp.ogg',
    'Db7': 'do_c7_sharp.ogg',
    'F7': 'fa_f7.ogg',
    'F#7': 'fa_f7_sharp.ogg',
    'Gb7': 'fa_f7_sharp.ogg',
    'A7': 'la_a7.ogg',
    'A#7': 'la_a7_sharp.ogg',
    'Hb7': 'la_a7_sharp.ogg',
    'G7': 'sol_g7.ogg',
    'G#7': 'sol_g7_sharp.ogg',
    'Ab7': 'sol_g7_sharp.ogg',
    'D7': 're_d7.ogg',
    'D#7': 're_d7_sharp.ogg',
    'Eb7': 're_d7_sharp.ogg',
    'E7': 'mi_e7.ogg',
    'H7': 'si_b7.ogg',

    'C6': 'do_c6.ogg',
    'C#6': 'do_c6_sharp.ogg',
    'Db6': 'do_c6_sharp.ogg',
    'F6': 'fa_f6.ogg',
    'F#6': 'fa_f6_sharp.ogg',
    'Gb6': 'fa_f6_sharp.ogg',
    'A6': 'la_a6.ogg',
    'A#6': 'la_a6_sharp.ogg',
    'Hb6': 'la_a6_sharp.ogg',
    'G6': 'sol_g6.ogg',
    'G#6': 'sol_g6_sharp.ogg',
    'Ab6': 'sol_g6_sharp.ogg',
    'D6': 're_d6.ogg',
    'D#6': 're_d6_sharp.ogg',
    'Eb6': 're_d6_sharp.ogg',
    'E6': 'mi_e6.ogg',
    'H6': 'si_b6.ogg',

    'C5': 'do_c5.ogg',
    'C#5': 'do_c5_sharp.ogg',
    'Db5': 'do_c5_sharp.ogg',
    'F5': 'fa_f5.ogg',
    'F#5': 'fa_f5_sharp.ogg',
    'Gb5': 'fa_f5_sharp.ogg',
    'A5': 'la_a5.ogg',
    'A#5': 'la_a5_sharp.ogg',
    'Hb5': 'la_a5_sharp.ogg',
    'G5': 'sol_g5.ogg',
    'G#5': 'sol_g5_sharp.ogg',
    'Ab5': 'sol_g5_sharp.ogg',
    'D5': 're_d5.ogg',
    'D#5': 're_d5_sharp.ogg',
    'Eb5': 're_d5_sharp.ogg',
    'E5': 'mi_e5.ogg',
    'H5': 'si_b5.ogg',

    'C4': 'do_c4.ogg',
    'C#4': 'do_c4_sharp.ogg',
    'Db4': 'do_c4_sharp.ogg',
    'F4': 'fa_f4.ogg',
    'F#4': 'fa_f4_sharp.ogg',
    'Gb4': 'fa_f4_sharp.ogg',
    'A4': 'la_a4.ogg',
    'A#4': 'la_a4_sharp.ogg',
    'Hb4': 'la_a4_sharp.ogg',
    'G4': 'sol_g4.ogg',
    'G#4': 'sol_g4_sharp.ogg',
    'Ab4': 'sol_g4_sharp.ogg',
    'D4': 're_d4.ogg',
    'D#4': 're_d4_sharp.ogg',
    'Eb4': 're_d4_sharp.ogg',
    'E4': 'mi_e4.ogg',
    'H4': 'si_b4.ogg',

    'C3': 'do_c3.ogg',
    'C#3': 'do_c3_sharp.ogg',
    'Db3': 'do_c3_sharp.ogg',
    'F3': 'fa_f3.ogg',
    'F#3': 'fa_f3_sharp.ogg',
    'Gb3': 'fa_f3_sharp.ogg',
    'A3': 'la_a3.ogg',
    'A#3': 'la_a3_sharp.ogg',
    'Hb3': 'la_a3_sharp.ogg',
    'G3': 'sol_g3.ogg',
    'G#3': 'sol_g3_sharp.ogg',
    'Ab3': 'sol_g3_sharp.ogg',
    'D3': 're_d3.ogg',
    'D#3': 're_d3_sharp.ogg',
    'Eb3': 're_d3_sharp.ogg',
    'E3': 'mi_e3.ogg',
    'H3': 'si_b3.ogg',

    'C2': 'do_c2.ogg',
    'C#2': 'do_c2_sharp.ogg',
    'Db2': 'do_c2_sharp.ogg',
    'F2': 'fa_f2.ogg',
    'F#2': 'fa_f2_sharp.ogg',
    'Gb2': 'fa_f2_sharp.ogg',
    'A2': 'la_a2.ogg',
    'A#2': 'la_a2_sharp.ogg',
    'Hb2': 'la_a2_sharp.ogg',
    'G2': 'sol_g2.ogg',
    'G#2': 'sol_g2_sharp.ogg',
    'Ab2': 'sol_g2_sharp.ogg',
    'D2': 're_d2.ogg',
    'D#2': 're_d2_sharp.ogg',
    'Eb2': 're_d2_sharp.ogg',
    'E2': 'mi_e2.ogg',
    'H2': 'si_b2.ogg',

    'C1': 'do_c1.ogg',
    'C#1': 'do_c1_sharp.ogg',
    'Db1': 'do_c1_sharp.ogg',
    'F1': 'fa_f1.ogg',
    'F#1': 'fa_f1_sharp.ogg',
    'Gb1': 'fa_f1_sharp.ogg',
    'A1': 'la_a1.ogg',
    'A#1': 'la_a1_sharp.ogg',
    'Hb1': 'la_a1_sharp.ogg',
    'G1': 'sol_g1.ogg',
    'G#1': 'sol_g1_sharp.ogg',
    'Ab1': 'sol_g1_sharp.ogg',
    'D1': 're_d1.ogg',
    'D#1': 're_d1_sharp.ogg',
    'Eb1': 're_d1_sharp.ogg',
    'E1': 'mi_e1.ogg',
    'H1': 'si_b1.ogg',

    'A#0': 'la_a0_sharp.ogg',
    'Hb0': 'la_a0_sharp.ogg',
    'H0': 'si_b0.ogg'
}



def play_note(note, duration):
    sound = pygame.mixer.Sound("sounds/" + notes[note])
    sound.play()
    time.sleep(duration)
    sound.stop()

